local_backend: true
publish_mode: editorial_workflow
site_url: http://localhost:3000
backend:
  name: git-gateway
  branch: main
media_folder: public/static
public_folder: static
i18n:
  structure: multiple_folders
  locales: [en, nl]
  default_locale: en

collections:
  - name: "pages"
    label: "Pages"
    i18n:
      structure: single_file
    files:
      - label: "Home"
        name: "home"
        file: "content/home.md"
        i18n: true
        delete: false
        fields:
          - { label: "Title", name: "title", widget: "string", i18n: true }
          - { label: "Intro", name: "intro", widget: "text", i18n: true }
          - label: "fold"
            name: "fold"
            i18n: true
            widget: "object"
            fields:
              - label: "Showcase"
                name: "showcase"
                widget: "relation"
                collection: "cases"
                search_fields: ["title", "caseid"]
                value_field: "{{slug}}|{{title}}|{{image}}"
                display_fields: ["title", "caseid"]
                multiple: false
              - { label: "Received an email", name: "received", widget: "string", i18n: true }
              - { label: "Family", name: "family", widget: "string", i18n: true }
          - label: "What we do"
            name: "whatwedo"
            widget: "object"
            collapsed: true
            i18n: true
            fields:
              - { label: title, name: title, widget: string, i18n: true }
              - { label: description, name: description, widget: text, i18n: true }
              - { label: t1, name: t1, widget: string, i18n: true }
              - { label: t2, name: t2, widget: string, i18n: true }
              - { label: t3, name: t3, widget: string, i18n: true }
          - label: "Our proudest work"
            name: "ourproudestwork"
            widget: "relation"
            collection: "cases"
            search_fields: ["title", "caseid"]
            value_field: "{{slug}}"
            display_fields: ["title", "caseid"]
            multiple: true
          - label: "Our mission"
            name: "ourmission"
            widget: "object"
            collapsed: true
            i18n: true
            fields:
              - { label: title, name: title, widget: string, i18n: true }
              - { label: description, name: description, widget: text, i18n: true }
              - { label: "Members", name: members, widget: string }
              - { label: "Total cases", name: totalcases, widget: string }
              - { label: "Vulnerable ips", name: ips, widget: string }
          - label: "Help us, help you"
            name: "helpushelpyou"
            widget: "object"
            collapsed: true
            i18n: true
            fields:
              - { label: title, name: title, widget: string, i18n: true }
              - { label: description, name: description, widget: text, i18n: true }
          - label: "Volunteer"
            name: "volunteer"
            widget: "object"
            collapsed: true
            i18n: true
            fields:
              - { label: title, name: title, widget: string, i18n: true }
              - {
                  label: checklist,
                  name: checklist,
                  widget: list,
                  allow_add: true,
                  i18n: true,
                  fields: [{ label: "Item", name: "item", widget: string }]
                }
          - label: "Partners"
            name: "partners"
            widget: "object"
            collapsed: true
            i18n: true
            fields:
              - { label: description, name: description, widget: text, i18n: true }
      - label: "Testimonials"
        name: "testimonials"
        file: "content/testimonials.md"
        i18n: true
        fields:
          - label: "Testimonials"
            name: "testimonials"
            widget: list
            i18n: true
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "role", name: "role", widget: "string", i18n: true }
              - { label: "Quote", name: "quote", widget: "text", i18n: true }
              - {
                  label: "Image",
                  name: "image",
                  widget: "image",
                  media_folder: "/public/static/testimonials",
                  required: false
                }

      - label: "FAQ"
        name: "faq"
        file: "content/faq.md"
        i18n: true
        fields:
          - label: "FAQ groups"
            name: "faqgroups"
            widget: list
            i18n: true
            fields:
              - { label: "heading", name: "heading", widget: "string", i18n: true }
              - {
                  label: "FAQs",
                  name: "faqs",
                  widget: list,
                  i18n: true,
                  fields:
                    [
                      { label: "Title", name: "title", widget: "string", i18n: true },
                      { label: "Description", name: "description", widget: "markdown", i18n: true }
                    ]
                }

  - label: "Cases"
    name: "cases"
    i18n:
      structure: multiple_folders
    folder: "content/cases"
    create: true
    identifier_field: caseid
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Case ID", name: "caseid", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Case closed", name: "closed", widget: "boolean", required: false }
      - { label: "Case link", name: "link", widget: "string" }
      - { label: "Case lead", name: "caselead", widget: "string" }
      - { label: "Image", name: "image", widget: "image", media_folder: "/public/static/cases", required: false }
      - label: "Researchers"
        name: "researchers"
        widget: list
        fields:
          - { label: "Name", name: "name", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }

  - name: "people"
    label: "People"
    i18n:
      structure: multiple_folders
    folder: "content/people"
    create: true
    slug: "{{slug}}"
    identifier_field: name
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Image", name: "image", widget: "image", media_folder: "/public/static/people", required: false }
      - { label: "Role", name: "role", widget: "string" }
      - { label: "Bio", name: "bio", widget: "text", i18n: true }
      - { label: "Links", name: "links", widget: "list", fields: [{ label: "Link", name: "link", widget: "string" }] }
      - {
          label: "Articles",
          name: "articles",
          widget: "relation",
          collection: "articles",
          multiple: true,
          value_field: "{{slug}}|{{title}}",
          search_fields: ["title"],
          display_fields: ["title"],
          required: false
        }
      - {
          label: "Cases",
          name: "cases",
          widget: "relation",
          collection: "cases",
          multiple: true,
          value_field: "{{slug}}|{{title}}",
          search_fields: ["title", "caseid"],
          display_fields: ["title", "caseid"],
          required: false
        }

  - name: "articles"
    label: "Articles"
    i18n:
      structure: multiple_folders
    folder: "content/articles"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Author",
          name: "author",
          widget: "relation",
          collection: "people",
          value_field: "{{slug}}|{{name}}",
          search_fields: ["name"],
          default: "string"
        }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }
