export const HomeCollection = {
  name: '_index',
  label: 'Home page',
  slug: '_index',
  i18n: {
    structure: 'multiple_files',
  },
  folder: 'content',
  create: false,
  fields: [
    {
      label: 'Title',
      name: 'title',
      widget: 'string',
      default: 'home',
      i18n: true,
    },
    {
      label: 'Opener',
      name: 'opener',
      widget: 'string',
      i18n: true,
    },
    {
      label: 'Intro',
      name: 'intro',
      widget: 'text',
      i18n: true,
    },
    {
      label: 'fold',
      name: 'fold',
      i18n: true,
      widget: 'object',
      fields: [
        {
          label: 'Showcase',
          name: 'showcase',
          widget: 'relation',
          collection: 'articles',
          search_fields: ['title', 'case.caseid'],
          value_field: '/newsroom/articles/{{slug}}',
          display_fields: ['title', 'case.caseid'],
          i18n: true,
          multiple: false,
        },
        {
          label: 'Received an email',
          name: 'received',
          widget: 'string',
          i18n: true,
        },
        {
          name: 'received_alt',
          label: 'Alt text for received image',
          widget: 'string',
          i18n: true,
        },
        {
          label: 'Family',
          name: 'family',
          widget: 'string',
          i18n: true,
        },
        {
          name: 'family_alt',
          label: 'Alt text for family image',
          widget: 'string',
          i18n: true,
        },
      ],
    },
    {
      name: 'whatwedo',
      label: 'What we do',
      widget: 'object',
      collapsed: true,
      i18n: true,
      fields: [
        {
          label: 'title',
          name: 'title',
          widget: 'string',
          i18n: true,
        },
        {
          label: 'description',
          name: 'description',
          widget: 'text',
          i18n: true,
        },
        {
          label: 't1',
          name: 't1',
          widget: 'string',
          i18n: true,
        },
        {
          label: 't1_Image',
          name: 't1_image',
          widget: 'image',
          public_folder: '/images/',
          media_folder: '/assets/images/',
          required: true,
          i18n: true,
        },
        {
          label: 't1_alt',
          name: 'Alt text for t1 image',
          widget: 'string',
          i18n: true,
        },
        {
          label: 't2',
          name: 't2',
          widget: 'string',
          i18n: true,
        },
        {
          label: 't2_Image',
          name: 't2_image',
          widget: 'image',
          public_folder: '/images/',
          media_folder: '/assets/images/',
          required: true,
          i18n: true,
        },
        {
          label: 't2_alt',
          name: 'Alt text for t2 image',
          widget: 'string',
          i18n: true,
        },
        {
          label: 't3',
          name: 't3',
          widget: 'string',
          i18n: true,
        },
        {
          label: 't3_Image',
          name: 't3_image',
          widget: 'image',
          public_folder: '/images/',
          media_folder: '/assets/images/',
          required: true,
          i18n: true,
        },
        {
          label: 't3_alt',
          name: 'Alt text for t3 image',
          widget: 'string',
          i18n: true,
        },
      ],
    },
    {
      name: 'helpushelpyou',
      label: 'Help us, help you',
      widget: 'object',
      collapsed: true,
      i18n: true,
      fields: [
        {
          label: 'title',
          name: 'title',
          widget: 'string',
          i18n: true,
        },
        {
          label: 'description',
          name: 'description',
          widget: 'text',
          i18n: true,
        },
      ],
    },
    {
      label: 'Volunteer',
      name: 'volunteer',
      widget: 'object',
      collapsed: true,
      i18n: true,
      fields: [
        {
          label: 'title',
          name: 'title',
          widget: 'string',
          i18n: true,
        },
        {
          label: 'checklist',
          name: 'checklist',
          widget: 'list',
          allow_add: true,
          i18n: true,
          fields: [
            {
              label: 'Item',
              name: 'item',
              widget: 'string',
            },
          ],
        },
      ],
    },
  ],
};
