name: build_and_test_no_deploy
run-name: Build and test website, but not deploy
on:
  pull_request:

jobs:
  build_and_test_no_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true
      - name: Install npm dependencies
        run: npm install
      - name: Fetch People Data
        # Dependabot can't access the secrets, so we skip the people step
        if: ${{ github.actor != 'dependabot[bot]' }}
        env:
          GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          GOOGLE_DRIVE_FOLDER_ID: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
        run: npm run gen-people
      - name: Build
        run: |
          npm run update-stats
          npm run cms-build
          hugo --minify
  #      - name: Test HTML code
  #        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
  #        with:
  #          root: public
  #      - name: Upload HTML test report
  #        uses: actions/upload-artifact@v3
  #        if: success() || failure() # Run even if we had an error
  #        with:
  #          name: html5validator_log
  #          path: log.log
